name: debug

on:
  push:
    branches: [master]

jobs:
  set-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set milestone to PR
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context.sha)
            const response = await github.repos.listPullRequestsAssociatedWithCommit({ owner: context.repo.owner, repo:context.repo.repo, commit_sha: context.sha })
            console.log(response.data)
