name: debug

on:
  push:
    branches: [master]

jobs:
  set-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set milestone to PR
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            const response = await github.issues.listPullRequestsAssociatedWithCommit(context.d1c7ad68c4e63b4d8ed7085c91164ad5518843b5)
            console.log(response.data)
