name: debug

on:
  push:
    branches: [master]

jobs:
  set-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set milestone to pull_requests
        uses: actions/github-script@v4
        with:
          script: |
            const pull_requests = await github.repos.listPullRequestsAssociatedWithCommit({ owner: context.repo.owner, repo:context.repo.repo, commit_sha: context.sha })
            if (pull_requests.data.length != 1) {
              console.log("Expect 1 pull request but found: " + pull_requests.data)
              exit 0
            }

            pull_number = pull_requests.data[0].number
            console.log(pull_number)
